tables:
  - name: abc_bank_position
    description: "The landing table holding data imported from the csv extracted by abc_bank"
    columns:
      - name: accountID
        description: The code for the account at abc_bank
        data_tests:
          - not_null
      - name: symbol
        description: The security symbol at abc_bank
        data_tests:
          - not_null
          - unique
      - name: description
        description: The name of the security at abc_bank
        data_tests:
          - not_null
      - name: exchange
        description: "The short name or code of the exchange where the security is traded"
        data_tests:
          - not_null
      - name: report_date
        description: >
          The date of the report was extracted by ABC Bank.
          We consider this position to be effective
          from this date forward, until a change is seen.
        data_tests:
          - not_null
      - name: quantity
        description: >
          The number of securities we hold in the portfolio
          in abc_bank as per report date
        data_tests:
          - not_null
      - name: cost_base
        description: >
          The cost that was paid for the securities 
          held at abc_bank as per the report date
        data_tests:
          - not_null
      - name: position_value
        description: >
          The value of securities in the portfolio
          as per the report date
        data_tests:
          - not_null
      - name: currency
        description: The monetary value of the positions
        data_tests:
          - not_null